### ISSUE TITLE
[JOSS review] Various questions

### ISSUE THREAD

**Issue by thelfer** [otvam/pypeec#7]
@otvam First of all, my sincere apologies for the review process which is much slower than what it should. My professional duties did not allow me to make it better.

I opened this issue mostly for discussion around the review.

Here are some questions associated with the review criteria of JOSS:

> Whether the software has already been cited in academic papers.

I did not find any by search `PyPEEC` in google scholar. Do you have any information on that matter ?

> About authorship

Would you precise the role of Charles R. Sullivan in the development of `PyPEEC` or the writing of the paper. According to the insights of the project, you seem to only contributor. Maybe a section describing the contributions of the authors would help in the paper (this seems to have become a common practice in most papers)

> Community guideline (https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines)

I did not section any `CONTRIBUTING.md` file in the sources, nor any dedicated sections in the documentation. Did I missed it ?
If you don't have one, feel free to get inspiration from this one for instance: https://github.com/thelfer/MFrontGenericInterfaceSupport/blob/master/CONTRIBUTING.md

> Are there automated tests or manual steps described so that the functionality of the software can be verified?

Would you comment on this ?

**Comment by otvam** [comment]
No problem for the delay!

> Whether the software has already been cited in academic papers.

Not yet. PyPEEC has only been released last September so it is still a bit early. PyPEEC is currently used in two U.S. National Science Foundation sponsored projects and these projects are expected to produce papers (probably next year). Additionally, I have already received emails from three universities and a company asking questions about PyPEEC usage, indicating that the tool is actually used. 


> About authorship

For PyPEEC itself, I've added the list of contributions in https://github.com/otvam/pypeec/blob/main/docs/content/about.rst. The contributions of Charles Sullivan are not into the programming itself but into the tool architecture and the "which/what/how" for the electromagnetic solver.

For the paper, the contributions are as following:
   - Myself: "Statement of Need", "Capabilities and Workflow", and "Solver Performance" (doing the benchmark)
   - Charles Sullivan: "Statement of Need" and "Solver Performance" (defining the benchmark)

I could include that in the paper. I am not sure what is the JOSS policy about that.


> Community guideline

The contributing file is located there: https://github.com/otvam/pypeec/blob/main/.github/CONTRIBUTING.md. I do agree that this location is strange but this is the GitHub preferred location. The same information are also in the documentation: https://github.com/otvam/pypeec/blob/main/docs/content/technical.rst 


> Are there automated tests or manual steps described so that the functionality of the software can be verified?

PyPEEC provides 19 different examples and a tutorial (all located in the `examples` folder). These examples are covering all the relevant functionalities of PyPEEC (different frequencies, materials, sources, distributed parameters, an-isotropic parameters, geometry input formats, etc.).

The automated tests are running all the examples and checking for eventual regressions (integration and end-to-end tests). The tests are running locally and with GitHub actions on different platforms (Linux, MacOS, Windows) and with different installation methods (requirements.txt, pyproject.toml, Conda).

**Comment by thelfer** [comment]
> I could include that in the paper. I am not sure what is the JOSS policy about that.

We may ask the editor about this :) @likeajumprope, is there any guidance about adding a description of the respective contributions of the authors. This seems to have became common practice in other journals.

**Comment by otvam** [comment]
To run the tests and coverage analysis locally, the shell scripts "scripts/run_tests.sh" and "scripts/run_coverage.sh" are used. These scripts are also used for the CI with GitHub actions.

The commit 3268a15a6d352d9328e0d95efd694365de826c78 adds all these information to the documentation.

**Comment by thelfer** [comment]
@otvam Thanks for closing the issue, I shall have done it myself.
